### ISSUE TITLE
[ogólne] - ikonki icomoon

### ISSUE THREAD

**Issue by Anavriinn** [Anavriinn/Gabrysia-Roszak--praktyki#2]

**Comment by kubaty007** [comment]
Do czego używasz fontawesome?
![obraz](https://user-images.githubusercontent.com/62720503/200258732-a50b3951-6d9e-43c8-bb39-c501496b5a33.png)

**Comment by Anavriinn** [comment]
w sumie po nic już usunęłam  👌👍

**Comment by kubaty007** [comment]
To możesz już z tym zrobić commita i spushować. We wiadomości daj coś w stylu "#2 - usunięcie fontawesome".
